#!/bin/bash

export BLUE=$'\033[0;34m'
export CLEAR_LINE=$'\r\033[K'
export GREEN=$'\033[0;32m'
export NC=$'\033[0m'
export NO_COLOR=$'\033[0m'
export RED=$'\033[0;31m'
export WHITE_BOLD=$'\033[1;37m'
export YELLOW=$'\033[1;33m'
