#!/bin/bash
################################################################################
#
# Spacemacs
#
################################################################################

set -eux -o pipefail

DIRECTORY="$HOME/.emacs.d"

if [ ! -d "$DIRECTORY" ]; then
    git clone https://github.com/syl20bnr/spacemacs "$DIRECTORY"
    (
        cd "$DIRECTORY"
        git checkout develop
    )

    # TODO: symlink templates

    echo "Done!"
else
    echo 'Spacemacs is already installed on this machine.'
fi
