#!/bin/bash
################################################################################
#
# NPM Packages
#
################################################################################

packages=(
  @anthropic-ai/claude-code
  @openai/codex
  prettier
  prettier-eslint
  prettier-eslint-cli
  tern
  ulid
)

for package in "${packages[@]}"
do
    npm install -g "$package"
done

# Ensure the new packages are available
nodenv rehash
