#!/bin/bash
################################################################################
#
# Powerline Fonts
#
################################################################################

set -eux -o pipefail

git clone https://github.com/powerline/fonts.git --depth=1
(
    cd fonts
    sh install.sh
)

rm -rfv fonts
