#!/bin/bash
################################################################################
#
# NPM Packages
#
################################################################################

packages=(
  prettier
  prettier-eslint
  prettier-eslint-cli
  tern
  ulid
)

for package in "${packages[@]}"
do
    npm install -g "$package"
done
