#!/usr/bin/env bash
################################################################################
#
# Powerline Fonts
#
################################################################################

git clone https://github.com/powerline/fonts.git --depth=1
pushd fonts > /dev/null
sh install.sh
popd > /dev/null
rm -rf fonts
