#!/bin/bash
################################################################################
#
# Powerline Fonts
#
################################################################################

git clone https://github.com/powerline/fonts.git --depth=1
pushd fonts > /dev/null || exit
sh install.sh
popd > /dev/null || exit
rm -rf fonts
