#!/usr/bin/env bash
################################################################################
#
# Powerline Fonts
#
################################################################################

git clone https://github.com/powerline/fonts.git --depth=1
pushd fonts
sh install.sh
popd
rm -rf fonts

