#!/bin/bash
################################################################################
#
# rbenv Plugins
#
################################################################################

mkdir -p "$(rbenv root)/plugins"

plugins=(
    'rbenv/rbenv-default-gems'
    'tpope/rbenv-ctags'
)

for plugin in "${plugins[@]}"
do
    plugin_name=$(echo "${plugin}" | cut -d '/' -f 2)
    plugin_repo="git@github.com:${plugin}.git"

    git clone "${plugin_repo}" "$(rbenv root)/plugins/${plugin_name}"
done
