#!/usr/bin/env bash
################################################################################
#
# Update
#
################################################################################

# Homebrew and Homebrew Packages
echo && echo "--> Updating Homebrew and Homebrew Packages"
brewup

# Gems
echo && echo "--> Updating Ruby Gems"
rubyup

# Vimrc
# https://github.com/amix/vimrc
echo && echo "--> Updating Vimrc from https://github.com/amix/vimrc"
vimup

# Spacemacs
# https://github.com/syl20bnr/spacemacs
echo && echo "--> Updating Spacemacs from https://github.com/syl20bnr/spacemacs"
spacemacsup
