#!/bin/bash
################################################################################
#
# Vimrc
#
################################################################################

DIRECTORY="$HOME/.vim_runtime"

if [ ! -d "$DIRECTORY" ]; then
    git clone --depth=1 https://github.com/amix/vimrc.git "$DIRECTORY"
    pushd "$DIRECTORY" > /dev/null || exit
    pip3 install requests
    sh install_awesome_vimrc.sh
    popd > /dev/null || exit
    echo "Done!"
else
    echo 'Vimrc is already installed on this machine.'
fi
