#!/bin/zsh

# Homebrew configuration
eval "$(/opt/homebrew/bin/brew shellenv)"

# Basic PATH configuration
export PATH="${HOME}/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/postgresql@16/bin:/usr/local/opt/curl/bin:${PATH}"

# pyenv configuration
PYENV_ROOT="$(pyenv root)"
export PYENV_ROOT
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# ruby-build installs a non-Homebrew OpenSSL for each Ruby version installed and these are never upgraded.
# To link Rubies to Homebrew's OpenSSL (which is upgraded) add the following to your ~/.zshrc:
# Note: this may interfere with building old versions of Ruby (e.g <2.4) that use OpenSSL <1.1.
RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"

# YJIT is a new JIT compiler for Ruby 3.1
RUBY_CONFIGURE_OPTS="--with-yjit ${RUBY_CONFIGURE_OPTS}"

export RUBY_CONFIGURE_OPTS