#!/bin/bash

# Homebrew configuration
eval "$(/opt/homebrew/bin/brew shellenv)"

# Basic PATH configuration
export PATH="${HOME}/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/curl/bin:${PATH}"

# PostgreSQL configuration
export PATH="/opt/homebrew/opt/postgresql@16/bin:${PATH}"

# pyenv configuration
PYENV_ROOT="$(pyenv root)"
export PYENV_ROOT
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# ruby-build installs a non-Homebrew OpenSSL for each Ruby version installed and these are never upgraded.
# To link Rubies to Homebrew's OpenSSL (which is upgraded) add the following to your ~/.zshrc:
# Note: this may interfere with building old versions of Ruby (e.g <2.4) that use OpenSSL <1.1.
RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"

# YJIT is a new JIT compiler for Ruby 3.1
RUBY_CONFIGURE_OPTS="--with-yjit ${RUBY_CONFIGURE_OPTS}"

export RUBY_CONFIGURE_OPTS

# Created by `pipx` on 2025-12-12 04:49:42
export PATH="$PATH:/Users/matthew/.local/bin"

# Use zoxide as cd replacement
export ZOXIDE_CMD_OVERRIDE=cd

# Added by Obsidian
export PATH="$PATH:/Applications/Obsidian.app/Contents/MacOS"
